##
##  Capsula -- Working Directory Encapsulation
##  Copyright (c) 2025 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under MIT <https://spdx.org/licenses/MIT>
##

MD012:
    maximum: 2

MD014: false

